package com.sethg.app.data.local

import android.content.Context
import com.google.gson.Gson
import com.sethg.app.domain.model.MaterialCategory
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.cos
import kotlin.math.pow
import kotlin.math.sqrt

// ── Zone-wise e-waste buying rates (₹/kg) ─────────────────────────────────────
// assets/ewaste_rates.json is generated by data/prices/build_rates.py from
// sourced, dated rate observations. Lookup order: city → zone → national.

enum class Zone { NORTH, WEST, SOUTH, EAST, CENTRAL, NORTHEAST }

data class City(
    val name: String,
    val state: String,
    val zone: Zone,
    val lat: Double,
    val lon: Double
)

data class RateRange(val low: Double, val high: Double)

data class ResolvedRate(
    val range: RateRange,
    val level: Level,
    val regionName: String      // "Raipur", "CENTRAL", "India"
) {
    enum class Level { CITY, ZONE, NATIONAL }
}

@Singleton
class PriceRateRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val gson: Gson
) {
    private companion object {
        const val ASSET = "ewaste_rates.json"
    }

    // ── JSON shape ────────────────────────────────────────────────────────────
    private data class RateJson(val low: Double, val high: Double)
    private data class CityJson(
        val name: String, val state: String, val zone: String,
        val lat: Double, val lon: Double,
        val rates: Map<String, RateJson>?
    )
    private data class TableJson(
        val updated: String,
        val cities: List<CityJson>,
        val zones: Map<String, Map<String, RateJson>>,
        val national: Map<String, RateJson>
    )

    private val table: TableJson by lazy {
        context.assets.open(ASSET).bufferedReader().use { gson.fromJson(it, TableJson::class.java) }
    }

    val updated: String get() = table.updated

    val cities: List<City> by lazy {
        table.cities.map { City(it.name, it.state, Zone.valueOf(it.zone), it.lat, it.lon) }
    }

    fun cityByName(name: String?): City? = cities.firstOrNull { it.name == name }

    /** Most specific rate available for this category in this city. */
    fun rateFor(category: MaterialCategory, city: City?): ResolvedRate? {
        val key = category.name
        if (city != null) {
            table.cities.firstOrNull { it.name == city.name }?.rates?.get(key)?.let {
                return ResolvedRate(RateRange(it.low, it.high), ResolvedRate.Level.CITY, city.name)
            }
            table.zones[city.zone.name]?.get(key)?.let {
                return ResolvedRate(RateRange(it.low, it.high), ResolvedRate.Level.ZONE, city.zone.name)
            }
        }
        return table.national[key]?.let {
            ResolvedRate(RateRange(it.low, it.high), ResolvedRate.Level.NATIONAL, "India")
        }
    }

    /** Nearest listed city — works offline, no reverse geocoding needed. */
    fun nearestCity(lat: Double, lon: Double): City? =
        cities.minByOrNull { c ->
            // Equirectangular approximation is plenty for picking the nearest city
            val x = (c.lon - lon) * cos(Math.toRadians((c.lat + lat) / 2))
            val y = c.lat - lat
            sqrt(x.pow(2) + y.pow(2))
        }
}
